spring.application.name=ReactiveUniversity
spring.r2dbc.url=r2dbc:postgresql://xxx:5432/university
spring.r2dbc.username=xxx
spring.r2dbc.password=xxx
jws.sharedKey=key
teacher=http://localhost:8081
student=https://university.ddnsfree.com
office=https://university.ddnsfree.com
# ===============================
# OAUTH2 CLIENT (CLIENT CREDENTIALS)
# ===============================
# ID rejestracji klienta (nazwa u?ywana w kodzie)
spring.security.oauth2.client.registration.service-b-client.client-id=office
# Sekret klienta (has?o aplikacji)
spring.security.oauth2.client.registration.service-b-client.client-secret=secret
# Typ grantu ? client credentials (service ? service)
spring.security.oauth2.client.registration.service-b-client.authorization-grant-type=client_credentials
# Provider, kt�ry wyda token (np. Keycloak)
spring.security.oauth2.client.registration.service-b-client.provider=keycloak
# ===============================
# OAUTH2 PROVIDER
# ===============================
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:9999/realms/ReactiveUniversity/protocol/openid-connect/token



